sale_order_blanket_order: add test reproducing call_off_order_count crash
_compute_call_off_order_count crashes on 18 because `_read_group` is called the Odoo 16 way.

Error message:
  ValueError: Order term 'blanket_order_id.id' is not a valid aggregate nor valid groupby